var GAME_LEVELS = [
  
  
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "     xxxx x xxxx x  x   xxxx   x    xxxx  x   x xxxx x         xx      xxxx     ",
   "     x  x x x    x  x   x  x   x    x     x   x x    x          x      x        ",
   "     xxxx x x    xxx    x  x   x    xxx   x   x xxx  x          x      xxxx     ",
   "     x    x x    x x    xxxx   x    x     x   x x    x          x         x     ",
   "     x    x x    x  x   x  x   x    x      x x  x    x          x         x     ",
   "     x    x xxxx x  x   x  x   xxxx xxxx   xxx  xxxx xxxx      xxx     xxxx     ",
   "                                                                                ",
   "                                                                o       D       ",
   "            @                                                                   ",
   "            F                                                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  
  
  
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x  @       xxxx       o                                                    x  ",
   "  x          x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "     @       xx       xx        x o x          x    xx               x   x   x               x                    ",
   "             x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xx  xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx   x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   
   ["xxxxxxxxxxxxxxxxxxxxx         xxx                                         ",
    "xxxxxxxxxxxxxxxxxxxxx      xxxxxxxx                             !!!!!!!!!!",
    "xxxxxxx xxx   xxxxxxx      xxxxxxxxxx                       !!!!!xx !!!!!!",
    "     x   xx    xx  xx      xxxxxxxxxx                     !!!xxxxxxx!!!!!!",	
    "                           xxxxxxxxxx                  !!!xxxxxxxxxxx!!xxx",
    " @                         xxxxxxxxxxx          xxx    vxxxxxxxxxxxxx!!xxx",
    "    xsssssssssssssssss=x   xxxxxxxxxxxx          xx        xxxxxx!!!!v!xxx",   
    "xxxxxSSSSSSSSSSSSSSSSSSx   xxxxxxxxxxxxx        xxxx     xxxxxxxxxxv   xxx",   
    "xxxxxxxSSSSxxxxSSSSSSxxx   xxxxxxxxxxxxxx      xxx          xxxxxx      xx",
    "xxxxxxxxxxxxxxxxxxxxxxxx o    x xx  x  x                   xxxx         xx",
    "xxxxxxxxxxxxxxxxxxxxxxxx o  o                              xx           xx",
    "xxxxxxxxxxxxxxxxxxxxxxxxfffff                                   o      xxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxfffxxxxxx              o          o       !!!!xxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxx    xxxxx!!!!xxxxxxx   !!!!xxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxx!!xxxxxxxxxxxxxxxxxxxxxxxx  xx xxx    xxxxxxxxxxx!xxxxxxxxxxxxxxxxxxx",
    "!!!!!!!!!xxxxxxxxxxxxxxxxxxxx            o xxxxxxxxx!!!!xxxxxxx!xxxxxx    ",
    "xxxx!!!!!!!xxxxxxxxxxxxxxxxx             xxxxxxxxxxxx!!xxxxx!!!!!xxxx    o",
    "xxxxxx!!x!!xxxxxxxxxxxxxxxxx    oxxxooxxxxxxxxxxxxxxxxxxxxxxx!!!!!      xx",
    "xxxxxx!!xx!!xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxv     xxx",
    "xxxxxxxxxx!!xxxxxxxxxxxxxxxx o  xx      xxxxxxxxxxxxxxxxxxxxxxxx       xxx",
    "xxxxxxx!!!!!xxxxxxxxxx!xxxxx                xxx    xx   xxxx xx      xxxxx",
    "xxxxxxx!!xxxxxxxxxxxx!!!xxxxxx                                          xx",	
    "xxxxxxx!!!!xxxxxxxxxx!!xxxxxxxxx                 o           o         o  ",   
    "xxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",	 
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",	
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    " @    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "  o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxx!!xxxxxxxx   xx   xxxxxxxxxxxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxxxxxxxxx     x   xxx  xx xxxxxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxxxxxxxxx!!!!!xxxxxxx    xx  xxxxxxxxxxxxxxxxxx",   
    "xxx   xxxxxx!xxxxxx!!!xxxxxx xxxxx     xxx  xxxxxxxxxxxx",
    "xxx   xxxxxx!!xxxxxxxxxxx!!xxx!!!x!!!xxxxxxxxxxxxxxxxxxx",	
    "xxx     xxxxxxx                    v xxxxxxxxxxxxxxxxxxx",   
    "xxx                          o          xxxxxxxxxxxxxxxx",   
    "xxx                 o xxxxxxxxxxx              xxxxxxxxx",   
    "xxx              xxxxx           xx    o           xxxxx",   
    "xxx                                  xxxxxxxx         xx",   
    "xx            x                x++                    xx",   
    "xx        xxxxxx              xxx                     xx",   
    "xx      xxxxxxxxx        ++  xxxxx           xxxxx    xx",
    "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    xx",	
    "xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    xx",   
    "xxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxx!!!!xxxxxxx    xx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xx",                                                           
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xx",   
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xx",
    "xxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx     xxxxxx        xx",	
    "xxxxxx             xxxxxxxxxxxxxx         xxx       xxxx",   
    "xxxxx                    xxxxxx                   xxxxxx",   
    "xxxx                                                xxxx",   
    "x xx                                                  xx",   
    "x  xx                                                  x",   
    "x                                                      x",   
    "x           xxxxx                                      x",   
    "x                    x      xxx                        x",
    "x                                 x                    x",	
    "x              <                        xx             x",   
    "x                                            xxxx      x",   
    "x                                                      x",   
    "x                                                   xxxx",   
    "                                          x            x",   
    "    o                                          x       x",   
    "     o         ssss          sssss     o               x",   
    "xxxxxxxxx!!xxxxSSSSxx!!!!!!xxSSSSSx!!xxxxxxxxxxxxxxxxxxx"],

   ["                                                      ",
    "                                                      ",
    "                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                            @                         ",
	"                       wwwwwwwwwww                    ",
	"                         wwwwwww                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"       o                                              ",
	"     mmmmm                                            ",
	"                                     mmmmm            ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                            mmmm                      ",
	"                                                      ",
	"   mmmmm                                              ",
	"                                                      ",
	"                                                      ",
	"                                   o                  ",
	"                               mmmmmm                 ",
	"                                                      ",
	"                   o                                  ",
	"                 mmmmm                                ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                                                      ",
	"                          o    o                      ",
	"                   mmmmmmmmmmmmmmmm                   ",
	"                                                      "],
	
	
	["                             ",
	 "x   x x x   x x   x xxxx xxxx",
	 "x   x x xx  x xx  x x    x  x",
	 "x x x x x x x x x x xx   xxx ",
	 "xx xx x x  xx x  xx x    x  x",
	 "x   x x x   x x   x xxxx x  x",
	 "                             ",
	 "   @                         ",
	 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
	
	
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
